import React, { useEffect, useState } from 'react'

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api'
const money = new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 })

async function request(path, options = {}) { const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('deyoungtech-token')}`, ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Request failed'); return data }
export default function Admin() {
  const [stats, setStats] = useState({}); const [products, setProducts] = useState([]); const [orders, setOrders] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = async () => { try { const [s, p, o] = await Promise.all([request('/admin/stats'), request('/admin/products'), request('/admin/orders')]); setStats(s.stats); setProducts(p.products); setOrders(o.orders) } catch (e) { setError(e.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const updateOrder = async (id, orderStatus) => { await request(`/admin/orders/${id}`, { method: 'PATCH', body: JSON.stringify({ orderStatus }) }); load() }
  if (loading) return <section className="admin-page"><p>Loading admin dashboard...</p></section>
  return <section className="admin-page"><div className="admin-head"><div><p className="eyebrow">DEYOUNGTECH ADMIN</p><h1>Store dashboard</h1></div><button className="button" onClick={load}>Refresh</button></div>{error && <p className="form-error">{error}</p>}<div className="stats-grid"><div><span>Active products</span><strong>{stats.products ?? 0}</strong></div><div><span>Orders</span><strong>{stats.orders ?? 0}</strong></div><div><span>Paid orders</span><strong>{stats.paidOrders ?? 0}</strong></div><div><span>Revenue</span><strong>{money.format(stats.revenue ?? 0)}</strong></div></div><div className="admin-section"><div className="section-head"><h2>Products</h2><span>{products.length} total</span></div><div className="admin-table">{products.map(p => <div className="admin-row" key={p._id}><div><strong>{p.name}</strong><span>{p.category}</span></div><span>{p.stock} in stock</span><strong>{money.format(p.price)}</strong></div>)}</div></div><div className="admin-section"><div className="section-head"><h2>Orders</h2><span>{orders.length} total</span></div><div className="admin-table">{orders.map(o => <div className="admin-row order-row" key={o._id}><div><strong>{o.reference}</strong><span>{o.customer?.name} · {o.customer?.email}</span></div><strong>{money.format(o.total)}</strong><select value={o.orderStatus} onChange={e => updateOrder(o._id, e.target.value)}><option value="pending">Pending</option><option value="processing">Processing</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select></div>)}</div></div></section>
}
