import React, { useMemo, useState } from 'react'
import { ArrowLeft, CheckCircle2, CreditCard, Truck } from 'lucide-react'
import api from '../services/api'

const money = new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 })

export default function Checkout({ cart, onBack, onComplete }) {
  const [form, setForm] = useState({ name: '', email: '', phone: '', address: '', city: '', state: '' })
  const [paymentMethod, setPaymentMethod] = useState('paystack'); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [order, setOrder] = useState(null)
  const subtotal = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart]); const shippingFee = subtotal >= 100000 ? 0 : 5000; const total = subtotal + shippingFee
  const submit = async e => { e.preventDefault(); setError(''); setSubmitting(true); try { const data = await api.createOrder({ customer: { name: form.name, email: form.email, phone: form.phone }, shippingAddress: { address: form.address, city: form.city, state: form.state, country: 'Nigeria' }, items: cart.map(item => ({ product: item._id || item.id, name: item.name, quantity: item.quantity })), paymentMethod }); if (paymentMethod === 'cash_on_delivery') { setOrder(data.order); onComplete?.(data.order); return } const payment = paymentMethod === 'paystack' ? await api.initializePaystack(data.order.reference) : await api.initializeFlutterwave(data.order.reference); window.location.href = payment.authorizationUrl || payment.paymentLink } catch (err) { setError(err.message); setSubmitting(false) } }
  if (order) return <section className="checkout-page"><div className="success-card"><CheckCircle2 size={52}/><p className="eyebrow">ORDER RECEIVED</p><h1>Thank you for your order.</h1><p>Your reference is <strong>{order.reference}</strong>.</p><p>Your cash-on-delivery order has been received and will be processed shortly.</p><button className="button dark" onClick={onBack}>Continue shopping</button></div></section>
  return <section className="checkout-page"><button className="back-link" onClick={onBack}><ArrowLeft size={17}/> Back to shopping</button><div className="checkout-layout"><form className="checkout-form" onSubmit={submit}><p className="eyebrow">CHECKOUT</p><h1>Complete your order</h1><div className="form-grid"><label>Full name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label><label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/></label><label>Phone<input required value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/></label><label>Address<input required value={form.address} onChange={e => setForm({ ...form, address: e.target.value })}/></label><label>City<input required value={form.city} onChange={e => setForm({ ...form, city: e.target.value })}/></label><label>State<input required value={form.state} onChange={e => setForm({ ...form, state: e.target.value })}/></label></div><div className="payment-options"><h3>Payment method</h3><label><input type="radio" checked={paymentMethod === 'paystack'} onChange={() => setPaymentMethod('paystack')}/><CreditCard size={18}/> Paystack</label><label><input type="radio" checked={paymentMethod === 'flutterwave'} onChange={() => setPaymentMethod('flutterwave')}/><CreditCard size={18}/> Flutterwave</label><label><input type="radio" checked={paymentMethod === 'cash_on_delivery'} onChange={() => setPaymentMethod('cash_on_delivery')}/><Truck size={18}/> Cash on delivery</label></div>{error && <p className="form-error">{error}</p>}<button className="button dark checkout-submit" disabled={submitting || !cart.length}>{submitting ? 'Processing...' : paymentMethod === 'cash_on_delivery' ? 'Place order' : 'Continue to payment'}</button></form><aside className="checkout-summary"><p className="eyebrow">SUMMARY</p><h2>Your order</h2>{cart.map(item => <div className="summary-item" key={item.id}><span>{item.name} × {item.quantity}</span><strong>{money.format(item.price * item.quantity)}</strong></div>)}<div className="summary-total"><span>Subtotal</span><strong>{money.format(subtotal)}</strong></div><div className="summary-total"><span>Shipping</span><strong>{shippingFee ? money.format(shippingFee) : 'Free'}</strong></div><div className="summary-grand"><span>Total</span><strong>{money.format(total)}</strong></div></aside></div></section>
}
